---
title: "Course Schedule"
tbl-colwidths: [5,8,15,10,5,5,5,5]
editor: visual
---

```{r}
#| label: setup
#| include: false

source("helper.R")
```

::: column-screen-inset-right
| Week | Date | Topic | Readings | Videos | Module | Slides | Assignments |
|:-------:|---------|---------|:-------:|:-------:|:-------:|:-------:|:-------:|
| [1](weeks/week-1.qmd "Week 1") | `r advdate(tues,0)` | Course Intro |  | [📺](https://youtu.be/eimM6pNkYjE "R and RStudio") | [📒](modules/module-1.1.qmd "Module 1.1") | [🖥️](slides/week-1.1.qmd "Module 1.2 slides") |  |
|  | `r advdate(thurs,0)` | Getting Started with Quarto | [📖](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/ "project-oriented workflow") | [📺](https://youtu.be/6QN9ZYURDFg "Quarto") | [📒](modules/module-1.2.qmd "Module 1.2") | [🖥️](slides/week-1.2.qmd "Module 1.2 slides") |  |
| [2](weeks/week-2.qmd "Week 2") | `r advdate(tues,1)` | Bar charts, histograms | [📖](https://r4ds.hadley.nz/data-import "r4ds, 7") [📖](https://r4ds.hadley.nz/data-visualize.html "r4ds, 2") | [📺](https://youtu.be/QG1oDJPoIio "Make a bar chart") [📺](https://youtu.be/-1YhCql-gMo "Make a histogram") | [📒](modules/module-2.1.qmd "Module 2.1") | [🖥️](slides/week-2.1.qmd "Module 2.1 slides") |  |
|  | `r advdate(thurs,1)` | Line charts, scatter plots | [📖](https://r4ds.hadley.nz/layers.html "r4ds, 10.1-10.4") [📖](https://r4ds.hadley.nz/communication.html#labels "r4ds, 12.2") | [📺](https://youtu.be/PnmQ2MFQpIc "Make a line chart") [📺](https://youtu.be/FiosjUVyfLM "Make a scatter plot") | [📒](modules/module-2.2.qmd "Module 2.2") | [🖥️](slides/week-2.2.qmd) | [📘](https://posit.cloud/spaces/787651 "Lab 1") |
| [3](weeks/week-3.qmd "Week 3") | `r advdate(tues,2)` | Downloading and manipulating data | [📖](https://r4ds.hadley.nz/data-transform.html#introduction "r4ds 3.1-3.4") | [📺](https://youtu.be/ScQD47eJeAE "Download data from V-Dem") | [📒](modules/module-3.1.qmd "Module 3.1") | [🖥️](slides/week-3.1.html "Module 3.1 slides") |  |
|  | `r advdate(thurs,2)` | Summarizing by groups | [📖](https://r4ds.hadley.nz/data-transform.html#introduction "r4ds 3.5") | [📺](https://youtu.be/mgBwVzMV-v8 "Summarizing data by groups") | [📒](modules/module-3.2.qmd "Module 3.2") | [🖥️](slides/week-3.2.html "Module 3.2 slides") | [📘](https://posit.cloud/spaces/787651 "Lab 2") |
| [4](weeks/week-4.qmd "Week 4") | `r advdate(tues,3)` | Homework 1: Visualize modernization theory | [📖](https://www-jstor-org.proxygw.wrlc.org/stable/1951731?seq=8 "Lipset") |  |  |  | [🧮](/assignments/homework-1.html "Homework 1") |
| [5](weeks/week-5.qmd "Week 5") | `r advdate(tues,4)` | Categorical data | [📖](https://openintro-ims.netlify.app/explore-categorical "IMS, chap. 4") | [📺](https://youtu.be/7NhNeADL8fA?si=InH8FFc1BIVT0ktM "Exploring Categorical Data") | [📒](modules/module-5.1.qmd "Module 5.1") | [🖥️](slides/week-5.1.qmd "Module 5.1 slides") |  |
|  | `r advdate(thurs,4)` | Continuous data | [📖](https://openintro-ims.netlify.app/explore-numerical "IMS, chap. 5.1 - 5.3") | [📺](https://youtu.be/Xm0PPtci3JE?si=MocqDt05YqllA9k5 "Exploring Numerical Data") | [📒](modules/module-5.2.qmd "Module 5.2") | [🖥️](slides/week-5.2.qmd "Module 5.2 slides") | [📘](https://posit.cloud/spaces/787651 "Lab 3") |
| [6](weeks/week-6.qmd "Week 6") | `r advdate(tues,5)` | Describing distributions | [📖](https://openintro-ims.netlify.app/explore-numerical#sec-variance-sd "IMS, chap. 5.4 - 5.5") |  | [📒](modules/module-6.1.qmd "Module 6.1") | [🖥️](slides/week-6.1.qmd "Module 6.1 slides") |  |
|  | `r advdate(thurs,5)` | Sampling and uncertainty | [📖](https://openintro-ims.netlify.app/foundations-bootstrapping "IMS, chap. 12") | [📺](https://www.youtube.com/watch?v=5q2ac412hv4 "The Right and Wrong Way to Interpret a CI") [📺](https://youtu.be/Xz0x-8-cgaQ?si=v_YCi-dU5YBdcb99 "Bootstrapping Main Ideas") | [📒](modules/module-6.2.qmd "Module 6.2") | [🖥️](slides/week-6.2.qmd "Module 6.2 slides") | [📘](https://posit.cloud/spaces/787651 "Lab 4") |
| [7](weeks/week-7.qmd "Week 7") | `r advdate(tues,6)` | Single proportion tests | [📖](https://openintro-ims.netlify.app/inference-one-prop "IMS, chap. 16") |  | [📒](modules/module-7.1.qmd "Module 7.1") | [🖥️](slides/week-7.1.qmd "Module 7.1 slides") |  |
|  | `r advdate(thurs,6)` | Differences between two groups | [📖](https://openintro-ims.netlify.app/foundations-randomization "IMS, chap. 11") | [📺](https://www.youtube.com/watch?v=2pHhjx9hyM4 "Using Randomization to Analyze Gender Discrimination") | [📒](modules/module-7.2.qmd "Module 7.2") | [🖥️](slides/week-7.2.qmd "Module 7.2 slides") | [📘](https://posit.cloud/spaces/787651 "Lab 5") |
| [8](weeks/week-8.qmd "Week 8") | `r advdate(tues,7)` | **No Class** | **Fall Break** 🍂 |  |  |  |  |
|  | `r advdate(thurs,7)` | Homework 2: Evaluate a claim | [📖](https://academic.oup.com/qje/article-abstract/127/4/1755/1841616 "Casey et. al.") |  |  |  | [🧮](/assignments/homework-2.html "Coding assignment 2") |
| [9](weeks/week-9.qmd "Week 9") | `r advdate(tues,8)` | Fitting a line to data | [📖](https://openintro-ims.netlify.app/model-slr#sec-fit-line-res-cor "IMS, chap. 7.1") | [📺](https://youtu.be/dLc-lfEEYss?si=-Zelb-HBAP-MPvnF "Linear Regression with One Variable, Part 1") [📺](https://youtu.be/KWULpBYzIYk?si=z_-wmdYlyrdpN4ys "Linear Regression with One Variable, Part 2") | [📒](modules/module-9.1.qmd "Module 9.1") | [🖥️](slides/week-9.1.qmd "Module 9.1 slides") |  |
|  | `r advdate(thurs,8)` | Least squares regression | [📖](https://openintro-ims.netlify.app/model-slr#sec-least-squares-regression "IMS, chap. 7.2") | [📺](https://youtu.be/CFN5zHzEuGY?si=uX_MFAbbSIzXMYQJ "Cost Function") [📺](https://youtu.be/peNRqkfukYY?si=UtakmQc9KLaQj7UH "Cost Function Intuition") | [📒](modules/module-9.2.qmd "Module 9.2") | [🖥️](slides/week-9.2.qmd "Module 9.2 slides") | [📘](https://posit.cloud/spaces/787651 "Lab 6") |
| [10](weeks/week-10.qmd "Week 10") | `r advdate(tues,9)` | Multiple linear regression | [📖](https://openintro-ims.netlify.app/model-mlr "IMS, chap. 8.1 and 8.2") | [📺](https://youtu.be/jXg0vU0y1ak?si=rhQ9uWhuhVqnI-Ox "Linear Regression with Multiple Variables") | [📒](modules/module-10.1.qmd "Module 10.1") | [🖥️](slides/week-10.1.qmd "Module 10.1 slides") |  |
|  | `r advdate(thurs,9)` | Dealing with outliers | [📖](https://openintro-ims.netlify.app/model-slr#sec-outliers-in-regression "IMS, chap. 7.3") [📖](https://openintro-ims.netlify.app/explore-numerical#sec-transforming-data "IMS, chap. 5.7") [📖](https://openintro-ims.netlify.app/inf-model-slr#sec-tech-cond-linmod "IMS, chap. 24.6") | [📺](https://youtu.be/OYwq0MlY11g?si=YV1JVOTqTLUJgk0U "What Should You Do With Outliers?") [📺](https://youtu.be/iMdtTCX2Q70?si=5qhftnJZ0jYRhmdB "Checking Model Assumptions with Residual Plots") | [📒](modules/module-10.2.qmd "Module 10.2") [📗](modules/module-10.3.qmd "Optional: Checking Model Assumptions") | [🖥️](slides/week-10.2.qmd "Module 10.2 slides") | [📘](https://posit.cloud/spaces/787651 "Lab 7") |
| [11](weeks/week-11.qmd "Week 11") | `r advdate(tues,10)` | Logistic regression | [📖](https://openintro-ims.netlify.app/model-logistic "IMS, chap. 9.1 and 9.2") | [📺](https://youtu.be/p-ltr1C7u2o?si=TLb3y75pSaJ067ue "Classification: Motivation") [📺](https://youtu.be/xuTiAW0OR40?si=sUoIr5pzHwHEpazO "Logistic Regression") | [📒](modules/module-11.1.qmd "Module 11.1") | [🖥️](slides/week-11.1.qmd "Module 11.1 slides") |  |
|  | `r advdate(thurs,10)` | Interpreting results |  | [📺](https://youtu.be/oIR8YOSXudM?si=aEALe2ifW71lsJJG "Odds Ratios in Logistic Regression") | [📒](modules/module-11.2.qmd "Module 11.2") | [🖥️](slides/week-11.2.qmd "Module 11.2 slides") | [📘](https://posit.cloud/spaces/787651 "Lab 8") |
| [12](weeks/week-12.qmd "Week 12") | `r advdate(tues,11)` | Multiple predictors and interactions | [📖](https://openintro-ims.netlify.app/model-logistic#logistic-model-with-many-variables "IMS, chap. 9.3 and 9.4") | [📺](https://youtu.be/eb5lGVHHlY0?si=BCQJhZHezE9ihLg3 "Effect Multipliers in Logistic Regression") | [📒](modules/module-12.1.qmd "Module 12.1") | [🖥️](slides/week-12.1.qmd "Module 12.1 slides") |  |
|  | `r advdate(thurs,11)` | Visualizing and communicating results |  | [📺](https://youtu.be/My6_X6x5TZw "Display Multiple Models with Model Summary") [📺](https://youtu.be/gif_wkqyub8 "Coefficient Plots for Single Models") | [📒](modules/module-12.2.qmd "Module 12.2") | [🖥️](slides/week-12.2.qmd "Module 12.2 slides") | [📘](https://posit.cloud/spaces/787651 "Lab 9") |
| [13](weeks/week-13.qmd "Week 13") | `r advdate(tues,12)` | Homework 3: Analyzing conflict |  |  |  |  | [🧮](/assignments/homework-3.html "Coding assignment 3") |
|  | `r advdate(tues,13)` | **No Class** | **Thanksgiving Break** |  |  🦃🍁🥧 |  |  |
| [14](weeks/week-14.qmd "Week 14") | `r advdate(tues,14)` | Final project workshop |  |  |  | [🖥️](slides/week-14.1.qmd "Module 14.1 slides") | [✍️](/project/project-description.qmd "Final project") |
|  | `r advdate(thurs,14)` | Final project workshop |  |  |  | [🖥️](slides/week-14.2.qmd "Module 14.2 slides") |  |
|  | `r advdate(tues,15)` | Final project workshop |  |  |  |  | [✍️](/project/project-description.qmd "Final project") |
:::
